{
    Chain0:
    map_text MapText.TorontoReactor 0 ; "Test string 0 (0)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain1:
    map_text MapText.TorontoReactor 1 ; "Test string 1 (1)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain2:
    map_text MapText.TorontoReactor 2 ; "Test string 2 (2)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain3:
    map_text MapText.TorontoReactor 3 ; "Test string 3 (3)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain4:
    map_text MapText.TorontoReactor 4 ; "Test string 4 (4)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain5:
    map_text MapText.TorontoReactor 5 ; "Test string 5 (5)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain6:
    map_text MapText.TorontoReactor 6 ; "Test string 6 (6)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain7:
    map_text MapText.TorontoReactor 7 ; "Test string 7 (7)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain8:
    map_text MapText.TorontoReactor 8 ; "Test string 8 (8)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain9:
    map_text MapText.TorontoReactor 9 ; "Test string 9 (9)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain10:
    map_text MapText.TorontoReactor 10 ; "Test string 10 (A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain11:
    map_text MapText.TorontoReactor 11 ; "Test string 11 (B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain12:
    map_text MapText.TorontoReactor 12 ; "Test string 12 (C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain13:
    map_text MapText.TorontoReactor 13 ; "Test string 13 (D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain14:
    map_text MapText.TorontoReactor 14 ; "Test string 14 (E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain15:
    map_text MapText.TorontoReactor 15 ; "Test string 15 (F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain16:
    map_text MapText.TorontoReactor 16 ; "Test string 16 (10)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain17:
    map_text MapText.TorontoReactor 17 ; "Test string 17 (11)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain18:
    map_text MapText.TorontoReactor 18 ; "Test string 18 (12)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain19:
    map_text MapText.TorontoReactor 19 ; "Test string 19 (13)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain20:
    map_text MapText.TorontoReactor 20 ; "Test string 20 (14)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain21:
    map_text MapText.TorontoReactor 21 ; "Test string 21 (15)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain22:
    map_text MapText.TorontoReactor 22 ; "Test string 22 (16)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain23:
    map_text MapText.TorontoReactor 23 ; "Test string 23 (17)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain24:
    map_text MapText.TorontoReactor 24 ; "Test string 24 (18)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain25:
    map_text MapText.TorontoReactor 25 ; "Test string 25 (19)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain26:
    map_text MapText.TorontoReactor 26 ; "Test string 26 (1A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain27:
    map_text MapText.TorontoReactor 27 ; "Test string 27 (1B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain28:
    map_text MapText.TorontoReactor 28 ; "Test string 28 (1C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain29:
    map_text MapText.TorontoReactor 29 ; "Test string 29 (1D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain30:
    map_text MapText.TorontoReactor 30 ; "Test string 30 (1E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain31:
    map_text MapText.TorontoReactor 31 ; "Test string 31 (1F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain32:
    map_text MapText.TorontoReactor 32 ; "Test string 32 (20)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain33:
    map_text MapText.TorontoReactor 33 ; "Test string 33 (21)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain34:
    map_text MapText.TorontoReactor 34 ; "Test string 34 (22)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain35:
    map_text MapText.TorontoReactor 35 ; "Test string 35 (23)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain36:
    map_text MapText.TorontoReactor 36 ; "Test string 36 (24)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain37:
    map_text MapText.TorontoReactor 37 ; "Test string 37 (25)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain38:
    map_text MapText.TorontoReactor 38 ; "Test string 38 (26)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain39:
    map_text MapText.TorontoReactor 39 ; "Test string 39 (27)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain40:
    map_text MapText.TorontoReactor 40 ; "Test string 40 (28)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain41:
    map_text MapText.TorontoReactor 41 ; "Test string 41 (29)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain42:
    map_text MapText.TorontoReactor 42 ; "Test string 42 (2A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain43:
    map_text MapText.TorontoReactor 43 ; "Test string 43 (2B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain44:
    map_text MapText.TorontoReactor 44 ; "Test string 44 (2C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain45:
    map_text MapText.TorontoReactor 45 ; "Test string 45 (2D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain46:
    map_text MapText.TorontoReactor 46 ; "Test string 46 (2E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain47:
    map_text MapText.TorontoReactor 47 ; "Test string 47 (2F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain48:
    map_text MapText.TorontoReactor 48 ; "Test string 48 (30)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain49:
    map_text MapText.TorontoReactor 49 ; "Test string 49 (31)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain50:
    map_text MapText.TorontoReactor 50 ; "Test string 50 (32)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain51:
    map_text MapText.TorontoReactor 51 ; "Test string 51 (33)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain52:
    map_text MapText.TorontoReactor 52 ; "Test string 52 (34)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain53:
    map_text MapText.TorontoReactor 53 ; "Test string 53 (35)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain54:
    map_text MapText.TorontoReactor 54 ; "Test string 54 (36)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain55:
    map_text MapText.TorontoReactor 55 ; "Test string 55 (37)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain56:
    map_text MapText.TorontoReactor 56 ; "Test string 56 (38)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain57:
    map_text MapText.TorontoReactor 57 ; "Test string 57 (39)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain58:
    map_text MapText.TorontoReactor 58 ; "Test string 58 (3A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain59:
    map_text MapText.TorontoReactor 59 ; "Test string 59 (3B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain60:
    map_text MapText.TorontoReactor 60 ; "Test string 60 (3C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain61:
    map_text MapText.TorontoReactor 61 ; "Test string 61 (3D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain62:
    map_text MapText.TorontoReactor 62 ; "Test string 62 (3E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain63:
    map_text MapText.TorontoReactor 63 ; "Test string 63 (3F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain64:
    map_text MapText.TorontoReactor 64 ; "Test string 64 (40)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain65:
    map_text MapText.TorontoReactor 65 ; "Test string 65 (41)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain66:
    map_text MapText.TorontoReactor 66 ; "Test string 66 (42)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain67:
    map_text MapText.TorontoReactor 67 ; "Test string 67 (43)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain68:
    map_text MapText.TorontoReactor 68 ; "Test string 68 (44)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain69:
    map_text MapText.TorontoReactor 69 ; "Test string 69 (45)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain70:
    map_text MapText.TorontoReactor 70 ; "Test string 70 (46)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain71:
    map_text MapText.TorontoReactor 71 ; "Test string 71 (47)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain72:
    map_text MapText.TorontoReactor 72 ; "Test string 72 (48)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain73:
    map_text MapText.TorontoReactor 73 ; "Test string 73 (49)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain74:
    map_text MapText.TorontoReactor 74 ; "Test string 74 (4A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain75:
    map_text MapText.TorontoReactor 75 ; "Test string 75 (4B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain76:
    map_text MapText.TorontoReactor 76 ; "Test string 76 (4C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain77:
    map_text MapText.TorontoReactor 77 ; "Test string 77 (4D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain78:
    map_text MapText.TorontoReactor 78 ; "Test string 78 (4E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain79:
    map_text MapText.TorontoReactor 79 ; "Test string 79 (4F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain80:
    map_text MapText.TorontoReactor 80 ; "Test string 80 (50)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain81:
    map_text MapText.TorontoReactor 81 ; "Test string 81 (51)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain82:
    map_text MapText.TorontoReactor 82 ; "Test string 82 (52)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain83:
    map_text MapText.TorontoReactor 83 ; "Test string 83 (53)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain84:
    map_text MapText.TorontoReactor 84 ; "Test string 84 (54)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain85:
    map_text MapText.TorontoReactor 85 ; "Test string 85 (55)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain86:
    map_text MapText.TorontoReactor 86 ; "Test string 86 (56)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain87:
    map_text MapText.TorontoReactor 87 ; "Test string 87 (57)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain88:
    map_text MapText.TorontoReactor 88 ; "Test string 88 (58)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain89:
    map_text MapText.TorontoReactor 89 ; "Test string 89 (59)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain90:
    map_text MapText.TorontoReactor 90 ; "Test string 90 (5A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain91:
    map_text MapText.TorontoReactor 91 ; "Test string 91 (5B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain92:
    map_text MapText.TorontoReactor 92 ; "Test string 92 (5C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain93:
    map_text MapText.TorontoReactor 93 ; "Test string 93 (5D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain94:
    map_text MapText.TorontoReactor 94 ; "Test string 94 (5E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain95:
    map_text MapText.TorontoReactor 95 ; "Test string 95 (5F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain96:
    map_text MapText.TorontoReactor 96 ; "Test string 96 (60)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain97:
    map_text MapText.TorontoReactor 97 ; "Test string 97 (61)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain98:
    map_text MapText.TorontoReactor 98 ; "Test string 98 (62)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain99:
    map_text MapText.TorontoReactor 99 ; "Test string 99 (63)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain100:
    map_text MapText.TorontoReactor 100 ; "Test string 100 (64)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain101:
    map_text MapText.TorontoReactor 101 ; "Test string 101 (65)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain102:
    map_text MapText.TorontoReactor 102 ; "Test string 102 (66)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain103:
    map_text MapText.TorontoReactor 103 ; "Test string 103 (67)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain104:
    map_text MapText.TorontoReactor 104 ; "Test string 104 (68)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain105:
    map_text MapText.TorontoReactor 105 ; "Test string 105 (69)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain106:
    map_text MapText.TorontoReactor 106 ; "Test string 106 (6A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain107:
    map_text MapText.TorontoReactor 107 ; "Test string 107 (6B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain108:
    map_text MapText.TorontoReactor 108 ; "Test string 108 (6C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain109:
    map_text MapText.TorontoReactor 109 ; "Test string 109 (6D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain110:
    map_text MapText.TorontoReactor 110 ; "Test string 110 (6E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain111:
    map_text MapText.TorontoReactor 111 ; "Test string 111 (6F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain112:
    map_text MapText.TorontoReactor 112 ; "Test string 112 (70)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain113:
    map_text MapText.TorontoReactor 113 ; "Test string 113 (71)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain114:
    map_text MapText.TorontoReactor 114 ; "Test string 114 (72)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain115:
    map_text MapText.TorontoReactor 115 ; "Test string 115 (73)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain116:
    map_text MapText.TorontoReactor 116 ; "Test string 116 (74)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain117:
    map_text MapText.TorontoReactor 117 ; "Test string 117 (75)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain118:
    map_text MapText.TorontoReactor 118 ; "Test string 118 (76)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain119:
    map_text MapText.TorontoReactor 119 ; "Test string 119 (77)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain120:
    map_text MapText.TorontoReactor 120 ; "Test string 120 (78)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain121:
    map_text MapText.TorontoReactor 121 ; "Test string 121 (79)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain122:
    map_text MapText.TorontoReactor 122 ; "Test string 122 (7A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain123:
    map_text MapText.TorontoReactor 123 ; "Test string 123 (7B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain124:
    map_text MapText.TorontoReactor 124 ; "Test string 124 (7C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain125:
    map_text MapText.TorontoReactor 125 ; "Test string 125 (7D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain126:
    map_text MapText.TorontoReactor 126 ; "Test string 126 (7E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain127:
    map_text MapText.TorontoReactor 127 ; "Test string 127 (7F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain128:
    map_text MapText.TorontoReactor 128 ; "Test string 128 (80)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain129:
    map_text MapText.TorontoReactor 129 ; "Test string 129 (81)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain130:
    map_text MapText.TorontoReactor 130 ; "Test string 130 (82)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain131:
    map_text MapText.TorontoReactor 131 ; "Test string 131 (83)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain132:
    map_text MapText.TorontoReactor 132 ; "Test string 132 (84)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain133:
    map_text MapText.TorontoReactor 133 ; "Test string 133 (85)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain134:
    map_text MapText.TorontoReactor 134 ; "Test string 134 (86)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain135:
    map_text MapText.TorontoReactor 135 ; "Test string 135 (87)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain136:
    map_text MapText.TorontoReactor 136 ; "Test string 136 (88)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain137:
    map_text MapText.TorontoReactor 137 ; "Test string 137 (89)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain138:
    map_text MapText.TorontoReactor 138 ; "Test string 138 (8A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain139:
    map_text MapText.TorontoReactor 139 ; "Test string 139 (8B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain140:
    map_text MapText.TorontoReactor 140 ; "Test string 140 (8C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain141:
    map_text MapText.TorontoReactor 141 ; "Test string 141 (8D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain142:
    map_text MapText.TorontoReactor 142 ; "Test string 142 (8E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain143:
    map_text MapText.TorontoReactor 143 ; "Test string 143 (8F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain144:
    map_text MapText.TorontoReactor 144 ; "Test string 144 (90)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain145:
    map_text MapText.TorontoReactor 145 ; "Test string 145 (91)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain146:
    map_text MapText.TorontoReactor 146 ; "Test string 146 (92)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain147:
    map_text MapText.TorontoReactor 147 ; "Test string 147 (93)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain148:
    map_text MapText.TorontoReactor 148 ; "Test string 148 (94)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain149:
    map_text MapText.TorontoReactor 149 ; "Test string 149 (95)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain150:
    map_text MapText.TorontoReactor 150 ; "Test string 150 (96)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain151:
    map_text MapText.TorontoReactor 151 ; "Test string 151 (97)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain152:
    map_text MapText.TorontoReactor 152 ; "Test string 152 (98)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain153:
    map_text MapText.TorontoReactor 153 ; "Test string 153 (99)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain154:
    map_text MapText.TorontoReactor 154 ; "Test string 154 (9A)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain155:
    map_text MapText.TorontoReactor 155 ; "Test string 155 (9B)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain156:
    map_text MapText.TorontoReactor 156 ; "Test string 156 (9C)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain157:
    map_text MapText.TorontoReactor 157 ; "Test string 157 (9D)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain158:
    map_text MapText.TorontoReactor 158 ; "Test string 158 (9E)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain159:
    map_text MapText.TorontoReactor 159 ; "Test string 159 (9F)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain160:
    map_text MapText.TorontoReactor 160 ; "Test string 160 (A0)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain161:
    map_text MapText.TorontoReactor 161 ; "Test string 161 (A1)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain162:
    map_text MapText.TorontoReactor 162 ; "Test string 162 (A2)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain163:
    map_text MapText.TorontoReactor 163 ; "Test string 163 (A3)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain164:
    map_text MapText.TorontoReactor 164 ; "Test string 164 (A4)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain165:
    map_text MapText.TorontoReactor 165 ; "Test string 165 (A5)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain166:
    map_text MapText.TorontoReactor 166 ; "Test string 166 (A6)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain167:
    map_text MapText.TorontoReactor 167 ; "Test string 167 (A7)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain168:
    map_text MapText.TorontoReactor 168 ; "Test string 168 (A8)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain169:
    map_text MapText.TorontoReactor 169 ; "Test string 169 (A9)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain170:
    map_text MapText.TorontoReactor 170 ; "Test string 170 (AA)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain171:
    map_text MapText.TorontoReactor 171 ; "Test string 171 (AB)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain172:
    map_text MapText.TorontoReactor 172 ; "Test string 172 (AC)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain173:
    map_text MapText.TorontoReactor 173 ; "Test string 173 (AD)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain174:
    map_text MapText.TorontoReactor 174 ; "Test string 174 (AE)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain175:
    map_text MapText.TorontoReactor 175 ; "Test string 175 (AF)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain176:
    map_text MapText.TorontoReactor 176 ; "Test string 176 (B0)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain177:
    map_text MapText.TorontoReactor 177 ; "Test string 177 (B1)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain178:
    map_text MapText.TorontoReactor 178 ; "Test string 178 (B2)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain179:
    map_text MapText.TorontoReactor 179 ; "Test string 179 (B3)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain180:
    map_text MapText.TorontoReactor 180 ; "Test string 180 (B4)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain181:
    map_text MapText.TorontoReactor 181 ; "Test string 181 (B5)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain182:
    map_text MapText.TorontoReactor 182 ; "Test string 182 (B6)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain183:
    map_text MapText.TorontoReactor 183 ; "Test string 183 (B7)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain184:
    map_text MapText.TorontoReactor 184 ; "Test string 184 (B8)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain185:
    map_text MapText.TorontoReactor 185 ; "Test string 185 (B9)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain186:
    map_text MapText.TorontoReactor 186 ; "Test string 186 (BA)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain187:
    map_text MapText.TorontoReactor 187 ; "Test string 187 (BB)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain188:
    map_text MapText.TorontoReactor 188 ; "Test string 188 (BC)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain189:
    map_text MapText.TorontoReactor 189 ; "Test string 189 (BD)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain190:
    map_text MapText.TorontoReactor 190 ; "Test string 190 (BE)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain191:
    map_text MapText.TorontoReactor 191 ; "Test string 191 (BF)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain192:
    map_text MapText.TorontoReactor 192 ; "Test string 192 (C0)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain193:
    map_text MapText.TorontoReactor 193 ; "Test string 193 (C1)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain194:
    map_text MapText.TorontoReactor 194 ; "Test string 194 (C2)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain195:
    map_text MapText.TorontoReactor 195 ; "Test string 195 (C3)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain196:
    map_text MapText.TorontoReactor 196 ; "Test string 196 (C4)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain197:
    map_text MapText.TorontoReactor 197 ; "Test string 197 (C5)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain198:
    map_text MapText.TorontoReactor 198 ; "Test string 198 (C6)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain199:
    map_text MapText.TorontoReactor 199 ; "Test string 199 (C7)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain200:
    map_text MapText.TorontoReactor 200 ; "Test string 200 (C8)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain201:
    map_text MapText.TorontoReactor 201 ; "Test string 201 (C9)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain202:
    map_text MapText.TorontoReactor 202 ; "Test string 202 (CA)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain203:
    map_text MapText.TorontoReactor 203 ; "Test string 203 (CB)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain204:
    map_text MapText.TorontoReactor 204 ; "Test string 204 (CC)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain205:
    map_text MapText.TorontoReactor 205 ; "Test string 205 (CD)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain206:
    map_text MapText.TorontoReactor 206 ; "Test string 206 (CE)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain207:
    map_text MapText.TorontoReactor 207 ; "Test string 207 (CF)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain208:
    map_text MapText.TorontoReactor 208 ; "Test string 208 (D0)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain209:
    map_text MapText.TorontoReactor 209 ; "Test string 209 (D1)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain210:
    map_text MapText.TorontoReactor 210 ; "Test string 210 (D2)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain211:
    map_text MapText.TorontoReactor 211 ; "Test string 211 (D3)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain212:
    map_text MapText.TorontoReactor 212 ; "Test string 212 (D4)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain213:
    map_text MapText.TorontoReactor 213 ; "Test string 213 (D5)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain214:
    map_text MapText.TorontoReactor 214 ; "Test string 214 (D6)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain215:
    map_text MapText.TorontoReactor 215 ; "Test string 215 (D7)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain216:
    map_text MapText.TorontoReactor 216 ; "Test string 216 (D8)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain217:
    map_text MapText.TorontoReactor 217 ; "Test string 217 (D9)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain218:
    map_text MapText.TorontoReactor 218 ; "Test string 218 (DA)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain219:
    map_text MapText.TorontoReactor 219 ; "Test string 219 (DB)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain220:
    map_text MapText.TorontoReactor 220 ; "Test string 220 (DC)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain221:
    map_text MapText.TorontoReactor 221 ; "Test string 221 (DD)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain222:
    map_text MapText.TorontoReactor 222 ; "Test string 222 (DE)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain223:
    map_text MapText.TorontoReactor 223 ; "Test string 223 (DF)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain224:
    map_text MapText.TorontoReactor 224 ; "Test string 224 (E0)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain225:
    map_text MapText.TorontoReactor 225 ; "Test string 225 (E1)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain226:
    map_text MapText.TorontoReactor 226 ; "Test string 226 (E2)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain227:
    map_text MapText.TorontoReactor 227 ; "Test string 227 (E3)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain228:
    map_text MapText.TorontoReactor 228 ; "Test string 228 (E4)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain229:
    map_text MapText.TorontoReactor 229 ; "Test string 229 (E5)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain230:
    map_text MapText.TorontoReactor 230 ; "Test string 230 (E6)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain231:
    map_text MapText.TorontoReactor 231 ; "Test string 231 (E7)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain232:
    map_text MapText.TorontoReactor 232 ; "Test string 232 (E8)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain233:
    map_text MapText.TorontoReactor 233 ; "Test string 233 (E9)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain234:
    map_text MapText.TorontoReactor 234 ; "Test string 234 (EA)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain235:
    map_text MapText.TorontoReactor 235 ; "Test string 235 (EB)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain236:
    map_text MapText.TorontoReactor 236 ; "Test string 236 (EC)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain237:
    map_text MapText.TorontoReactor 237 ; "Test string 237 (ED)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain238:
    map_text MapText.TorontoReactor 238 ; "Test string 238 (EE)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain239:
    map_text MapText.TorontoReactor 239 ; "Test string 239 (EF)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain240:
    map_text MapText.TorontoReactor 240 ; "Test string 240 (F0)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain241:
    map_text MapText.TorontoReactor 241 ; "Test string 241 (F1)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain242:
    map_text MapText.TorontoReactor 242 ; "Test string 242 (F2)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain243:
    map_text MapText.TorontoReactor 243 ; "Test string 243 (F3)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain244:
    map_text MapText.TorontoReactor 244 ; "Test string 244 (F4)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain245:
    map_text MapText.TorontoReactor 245 ; "Test string 245 (F5)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain246:
    map_text MapText.TorontoReactor 246 ; "Test string 246 (F6)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain247:
    map_text MapText.TorontoReactor 247 ; "Test string 247 (F7)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain248:
    map_text MapText.TorontoReactor 248 ; "Test string 248 (F8)"
    change_language PartyMember.Tom SetToMaximum Celtic
}

{
    Chain249:
    map_text MapText.TorontoReactor 249 ; "Test string 249 (F9)"
    change_language PartyMember.Tom SetToMaximum Celtic
}
